### ISSUE TITLE
can you please share downloaded CT images and label?

### ISSUE THREAD

**Issue by shiyu2011** [assassint2017/abdominal-multi-organ-segmentation#5]
The original CT data from https://www.synapse.org/#!Synapse:syn3193805/wiki/89480 has been removed. Now all images which can be downloaded are MRI images? Can you share the data downloaded?

**Comment by SwanKnightZJP** [comment]
Maybe you should register an account first？ 
If you successfully joined the challenge from the link you metioned before, you may find what you want in the files.
（PS：If you come from mainland China, be mentally prepared, because that resource is really too difficult to download.）

**Comment by shiyu2011** [comment]
I did registration. I could download all data they allowed to download. But none of them are CT images

**Comment by SwanKnightZJP** [comment]
If you successfully joined this challeng, you may see the page like this.
![SharedScreenshot](https://user-images.githubusercontent.com/37257181/67858670-ba201480-fb54-11e9-9ad7-b9b5e9a326f0.jpg)
And you should also see some files which were previously invisible.
Then download the file which was circled. That is the CT data in need.
![SharedScreenshot1](https://user-images.githubusercontent.com/37257181/67858679-bb514180-fb54-11e9-94ff-bb25bbe71538.jpg)
All imgs and labels are saved in the form of .nii

**Comment by shiyu2011** [comment]
Yes, I got it following your instruction. Thanks you very much
